/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.angerm

import com.linecorp.armeria.server.Server

fun main() {
    val sb = Server.builder()
    val server = sb.build()
    server.start().join()
}
