name: CI
on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'corretto'
          java-version: 17

      - name: Test
        run: |
          pwd
          ls -alh
          ./gradlew test jacocoTestReport

      - name: Build
        run: ./gradlew build -x test

      - name: CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./base/build/reports/jacoco/report.xml,./database/build/reports/jacoco/report.xml,./grpc/build/reports/jacoco/report.xml,./redis/build/reports/jacoco/report.xml
