name: CI
on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: 17

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          pwd
          ls -alh
          ./gradlew test

      - name: Build
        run: ./gradlew build -x test
